baseURL = 'https://zyuegege.github.io/zyuegege/'
languageCode = 'zh-Hans'
title = 'Alvin的个人记录'
theme = 'smigle'

summaryLength = 1

defaultContentLanguage = 'zh-hans'
defaultContentLanguageInSubdir = false
disableDefaultLanguageRedirect = false
disableLanguages = []

[languages]
[languages.zh-hans]
disabled = false
languageCode = 'zh-hans'
languageDirection = 'ltr'
languageName = '简体中文'
title = 'Alvin的个人主页'
weight = 0

[menu]
[[menu.main]]
identifier = 'home'
name = '主页'
url = '/'
weight = '1'

[[menu.main]]
identifier = 'about'
name = '关于'
url = '/about/'
weight = '2'

[[menu.main]]
identifier = 'posts'
name = '文章'
url = '/posts/'
weight = '3'

[[menu.main]]
identifier = 'categories'
name = '类别'
url = '/categories/'
weight = '4'

[[menu.main]]
identifier = 'tags'
name = '标签'
url = '/tags/'
weight = '5'

[[menu.main]]
identifier = 'rss'
name = '订阅'
url = '/index.xml'
weight = '6'


[params]
abbrDateFmt = "Jan 2"
author = "Alvin Zhang"
brandIconFile = "images/brandIcon.svg"
dateFmt = "2006-01-02"
subtitle = "日常文章记录"


# params:
#   abbrDateFmt: "Jan 2"
#   author: "Blog Author"
#   brandIconFile: "images/brandIcon.svg"
#   dateFmt: "2006-01-02"
#   ##
#   ## Options for overriding theme or page defaults
#   ##
#   #customStylesheets: # Use to override theme styles, like logo size
#   #  - "css/custom.css"
#   #readingSpeed: 600 # Use to set custom reading speed
#   #readingSpeedMin: 25 # Use to set custom reading speed range
#   #readingSpeedMax: 175 # Use to set custom reading speed range
#   social:
#     - name: GitHub
#       url: https://github.com/ian-s-mcb
#     - name: GitLab
#       url: https://gitlab.com/ian-s-mcb
#     - name: Quizlet
#       url: https://quizlet.com/ian-s-mcb
#     - name: Reddit
#       url: https://www.reddit.com/user/ian-s-mcb
#     - name: StackOverflow
#       url: https://stackoverflow.com/users/3417846/ian-s-mcb
#   subtitle: "Description about Blog Author"
