baseURL = 'https://zyuegege.github.io/zyuegege/'
languageCode = 'zh-hans'
title = 'Alvin的个人记录'
theme = 'smigle'

[menu]

main = [
    {identifier='home', name='主页', url='/zyuegege/', weight='1'},
    {identifier='about', name='关于', url='/zyuegege/about/', weight='2'},
    {identifier='posts', name='文章', url='/zyuegege/posts/', weight='3'},
    {identifier='categories', name='类别', url='/zyuegege/categories/', weight='4'},
    {identifier='tags', name='标签', url='/zyuegege/tags/', weight='5'},
    {identifier='rss', name='订阅', url='/zyuegege/index.xml', weight='6'}
]

[params]
abbrDateFmt = "Jan 2"
author = "Alvin Zhang"
brandIconFile = "images/brandIcon.svg"
dateFmt = "2006-01-02"
subtitle = "日常文章记录"


# params:
#   abbrDateFmt: "Jan 2"
#   author: "Blog Author"
#   brandIconFile: "images/brandIcon.svg"
#   dateFmt: "2006-01-02"
#   ##
#   ## Options for overriding theme or page defaults
#   ##
#   #customStylesheets: # Use to override theme styles, like logo size
#   #  - "css/custom.css"
#   #readingSpeed: 600 # Use to set custom reading speed
#   #readingSpeedMin: 25 # Use to set custom reading speed range
#   #readingSpeedMax: 175 # Use to set custom reading speed range
#   social:
#     - name: GitHub
#       url: https://github.com/ian-s-mcb
#     - name: GitLab
#       url: https://gitlab.com/ian-s-mcb
#     - name: Quizlet
#       url: https://quizlet.com/ian-s-mcb
#     - name: Reddit
#       url: https://www.reddit.com/user/ian-s-mcb
#     - name: StackOverflow
#       url: https://stackoverflow.com/users/3417846/ian-s-mcb
#   subtitle: "Description about Blog Author"
